# Generated by Django 3.2.18 on 2023-05-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certno', models.BooleanField(primary_key=True, serialize=False)),
                ('certname', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'certificate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genno', models.IntegerField(primary_key=True, serialize=False)),
                ('genname', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movno', models.IntegerField(primary_key=True, serialize=False)),
                ('movname', models.CharField(blank=True, max_length=100, null=True)),
                ('runtimemin', models.IntegerField(blank=True, null=True)),
                ('dirname', models.CharField(blank=True, max_length=50, null=True)),
                ('actname', models.CharField(blank=True, max_length=150, null=True)),
                ('movintro', models.CharField(blank=True, max_length=1200, null=True)),
                ('distname', models.CharField(blank=True, max_length=100, null=True)),
                ('lang', models.CharField(blank=True, max_length=50, null=True)),
                ('imageurl', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
    ]
